version: '2'
config:
  slack_notify: true
  slack_channel: batman-ci
environment:
  BUILD_IMAGE: 'maven:3.6-jdk-11'
jobs:
  build:
    docker:
      - image:
          name: '{{ .env.BUILD_IMAGE }}'
    steps:
      - restore_cache:
          key: batman
      - run:
          name: 'Run command'
          command: 'mvn clean package -DskipTests'
      - save_cache:
          key: batman
          paths:
            - /root/.m2
  build_docker:
    steps:
      - build_image
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: marketplace
          workload: batman
          spinnaker_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-marketplace-prod
          namespace: default
          workload: batman
          spinnaker_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - master
deployment_config:
  dev:
    envVars:
      gridgo_profile: uat
    ingress:
      hosts:
        - host: batman.dev.tiki.services
          paths:
            - path: /
              port: '80'
    replicaCount: 1
  prod:
    envFrom:
    - secretRef:
        name: env-batman
        optional: null
    ingress:
      hosts:
        - host: batman.tiki.services
          paths:
            - path: /
              port: '80'
    replicaCount: 1
